
#projects = [ '../../data/vnc-tight/', ]
#projects = [ '../../data/firebird/', ]
#projects = [ '../../data/jedit/', ]
#projects = [ '../../data/ultravnc/', ]
#projects = [ '../../data/eclipse-cs/', ]
#projects = [ '../../data/springframework/', ]
#projects = [ '../../data/hibernate/', '../../data/azureus' ]
#projects = [ '../../data/squirrel-sql/', ]
#projects = [ '../../data/freemind/', ]
#projects = [ '../../data/mingw/', ]
#projects = [ '../../data/ant/', ]
#projects = [ '../../data/jetty/', ]
projects = [ '../../data/guava/' ]
#projects = [ '../../data/flink/', ]
